version: "3.7"
services:
  http-server:
    build:
      dockerfile: ./docker/go/Dockerfile
      context: .
    ports:
      - "6660:6660"
    volumes:
      - ./:/app
    environment:
      PORT: "6660"
